### ISSUE TITLE
--hash-only

### ISSUE THREAD

**Issue by gkiely** [thdk/package-changed#10]
install-changed has a way of updating the hash via `--hash-only`, does package-changed also have this ability from the command line?

**Comment by thdk** [comment]
Not really but would the following work for you?

`npx package-changed run "echo 'hash updated' " `

**Comment by thdk** [comment]
@gkiely I'll close this issue, feel free to reopen if my suggestion does not help you. If not please provide a use case so I can consider the need for `--hash-only`.

**Comment by gkiely** [comment]
This is my use case.
Command: `npm run install-latest`

```sh
npm i $(npm run -s get-latest) && npx playwright install chromium && install-changed --hash-only &>/dev/null
```

Hash only prevents running install again.

**Comment by thdk** [comment]
> This is my use case.
> Command: `npm run install-latest`
> 
> ```sh
> npm i $(npm run -s get-latest) && npx playwright install chromium && install-changed --hash-only &>/dev/null
> ```
> 
> Hash only prevents running install again.

@gkiely 
`npx package-changed run "npm i $(npm run -s get-latest) && npx playwright install chromium"`

Above line should do what you want. I'm writing this from my phone but check the docs for the 'run' command to see correct usage.
