### ISSUE TITLE
support pnpm, yarn, etc

### ISSUE THREAD

**Issue by dhorkin** [thdk/package-changed#14]
The `install-changed` package has a `--install-command` flag that allows you to use a different command than `npm i` to install, for example, `pnpm i`.

Given `package-changed` has some cool options like `--lockfile`, I'd like to make the switch, but don't want to get locked into npm.

PNPM still uses the `package.json` file, but it uses `pnpm-lock.yaml` instead of `package-lock.json` for lockfile, so it might not be so easy to make work with `--lockfile`, but otherwise, could probably be a pretty easy addition.

**Comment by thdk** [comment]
Hi,

You aren't locked into npm as long as you aren't using --lockfile option.

Not that this --lockfile option shouldn't have been there imho but there was a demand so I merged that feature request.

What is your use case for using package-changed? And especially for using the --lockfile?

(I see the latest version of install-changed still doesn't have the --install-command flag)

**Comment by dhorkin** [comment]
My main use case is ensuring everyone running code is running the exact same set of dependencies, and ensuring that the package-locks are always updated and committed.

I didn't realize that you could customize the install command with package-changed. I don't really have a lot of need for --lockfile, tbh.

And yeah, you have to install `install-changed` from github rather than npm to get that

**Comment by nemchik** [comment]
I've started working on proper support for `bun`, `pnpm`, and `yarn` in https://github.com/nemchik/package-changed/tree/dev
My changes likely do not address #16 
@thdk maybe we can chat about the changes I have in that branch (yes I know it's one giant commit)
I've tested it with `npm` and `pnpm` so far, no issues. The only breaking change is lockfile hashes being enabled by default.
