### ISSUE TITLE
Consider husky examples

### ISSUE THREAD

**Issue by nemchik** [thdk/package-changed#8]
I've just setup https://github.com/typicode/husky with

```shell
npx husky add .husky/post-checkout "npx --no package-changed"
npx husky add .husky/post-merge "npx --no package-changed"
npx husky add .husky/post-rebase "npx --no package-changed"
```

and added `.packagehash` to my `.gitignore` and this seems to work very well.

Would you consider adding something to the readme that would help others figure out how to attain this setup, or something similar (maybe there's a better way?)

**Comment by thdk** [comment]
Hi, @nemchik I wouldn't mind a PR adding a section to the readme with this. However, I am just wondering. How long does `npm install` takes for you when there are no changes? (without using package-changed).

For example, I am using yarn and running an (unneeded) install takes less that 500ms. Recent npm versions should be just as fast.

package-changed still has its use for some usecases, but it's worth looking into built in solutions or alternatives for both yarn and npm. Offline cache, global cache, pnp, zero installs, turborepo, ...

**Comment by nemchik** [comment]
> How long does `npm install` takes for you when there are no changes? (without using package-changed).

So I did some testing on my machine:

| Spec | Value |
|---|---|
| CPU | AMD Ryzen 7 3700X |
| Memory | 32 GB (I'm not sure of the exact specs, it's a work PC I didn't build) |
| Disk | WD_BLACK SN750 NVMe |
| OS | Windows 10 |
| node | 16.16.0 |
| npm | 8.19.0 |
| yarn | 1.22.19 |

I created a brand new empty folder and ran `npm init` inside it, then ran `npm install` to install dependencies (no dependencies, just an empty initialized npm project). I then ran `Measure-Command { npm install }` in powershell multiple times, and on average it took 1225ms.

I created a brand new empty folder and ran `yarn init` inside it, then ran `yarn install` to install dependencies (no dependencies, just an empty initialized yarn project). I then ran `Measure-Command { yarn install }` in powershell multiple times, and on average it took 220ms.

I expected that to be a poor test. So I copied an existing project I had with 14 dependencies (resulting in over 500 subfolders in `node_modules`) to a new folder and deleted the `node_modules` folder and the `package-lock.json` and then made two copies of the resulting folder. In one I ran `npm install` and in the other I ran `yarn install`. I then measured both.

npm: 3100ms
yarn: 810ms

Lastly, I tested `Measure-Command { npx package-changed }` in each of the 4 folders from above (npm existing/new, yarn existing/new) and got pretty much the same result in each, which is `1300ms` (when there have not been changes requiring action).

So, yes, adding git hooks (via husky, or any other method) will result in the git command running the hook being slower, but that's going to be the trade off no matter what. One of the most common uses I see of git hooks in node projects is https://github.com/okonet/lint-staged which is usually setup to run https://prettier.io/ as a pre-commit hook.

Anyway, I'll open a PR to add some info about the setup above.

Is it expected to keep `.packagehash` in `.gitignore`? I imagine if it's not then `package-changed` wouldn't be aware of changes when switching branches?
